yarnPath: .yarn/releases/yarn-3.5.1.cjs
packageExtensions:
  posthtml-component@*:
    dependencies:
      posthtml: "*"
  posthtml-expressions@*:
    dependencies:
      posthtml: "*"
  posthtml-beautify@*:
    dependencies:
      posthtml: "*"
